[env:esp32c3]
platform = espressif32
board = lolin_c3_mini
framework = arduino
monitor_speed = 115200
build_flags = -std=gnu++2a -DMRM_LOG=1
build_unflags = -std=gnu++11
board_build.filesystem = littlefs
lib_deps = https://github.com/gustavosilveiragss/marmota-fmk.git#v0.5.0
